import "@/globals.css";
import Providers from "./providers";
import ProtectedLayout from "@/components/Layout/ProtectedLayout";
import Navbar from "@/components/Navbar/Navbar";
import { cookies, headers } from "next/headers";

export const metadata = {
  title: "Point of Sale System",
  description: "Generated by create next app",
};

const isAuthenticated = async () => {
  const cookieStore = cookies();
  const token = cookieStore.get(process.env.NEXT_PUBLIC_TOKEN);
  return token ? true : false;
};

// implement fetchOptions to all api requests first before proceeding define products with initial state
const RootLayout = async ({ children }) => {
  const currentPath = headers().get("currentPath") || "/";
  const publicPaths = ["/", "/register"];

  const authenticated = await isAuthenticated();

  return (
    <Providers>
      <html lang="en">
        <body className="antialiased w-screen h-screen m-0 p-0 flex flex-col">
          <Navbar />
          <main className="flex flex-1 h-[90%]">
            {authenticated && !publicPaths.includes(currentPath) ? (
              <ProtectedLayout> {children}</ProtectedLayout>
            ) : (
              <>{children}</>
            )}
          </main>
          <footer></footer>
        </body>
      </html>
    </Providers>
  );
};

export default RootLayout;
