import "@/globals.css";
import Providers from "./providers";
import ToastProvider from "@/components/toast/ToastProvider";
import { SkeletonTheme } from "react-loading-skeleton";

export const metadata = {
  title: "Inventory Management System",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  return (
    <SkeletonTheme baseColor="#d1e0e0" highlightColor="#edf7f6">
      <Providers>
        <html lang="en">
          <body className="antialiased w-screen h-screen m-0 p-0">
            <main className="h-full w-full overflow-hidden">{children}</main>
            <ToastProvider />
          </body>
        </html>
      </Providers>
    </SkeletonTheme>
  );
};

export default RootLayout;
